[versions]
io-quarkus = "3.6.4"
quarkus-mybatis = "2.2.0"
com-diffplug-spotless = "6.23.2"

[libraries]
quarkus-bom = { group = "io.quarkus.platform", name = "quarkus-bom", version.ref = "io-quarkus" }
quarkus-resteasy-reactive-jackson = { group = "io.quarkus", name = "quarkus-resteasy-reactive-jackson" }
quarkus-hibernate-validator = { group = "io.quarkus", name = "quarkus-hibernate-validator" }
quarkus-jdbc-postgresql = { group = "io.quarkus", name = "quarkus-jdbc-postgresql" }
quarkus-arc = { group = "io.quarkus", name = "quarkus-arc" }
quarkus-resteasy-reactive = { group = "io.quarkus", name = "quarkus-resteasy-reactive" }
quarkus-mybatis = { group = "io.quarkiverse.mybatis", name = "quarkus-mybatis", version.ref = "quarkus-mybatis" }
quarkus-logging-json = { group = "io.quarkus", name = "quarkus-resteasy-reactive" }
quarkus-junit5 = { group = "io.quarkus", name = "quarkus-resteasy-reactive" }

[plugins]
io-quarkus = { id = "io.quarkus", version.ref = "io-quarkus" }
com-diffplug-spotless = { id = "com.diffplug.spotless", version.ref = "com-diffplug-spotless" }

[bundles]
