spring:
  datasource:
    url: jdbc:aws-wrapper:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?wrapperProfileName=datasource-with-internal-connection-pool&readerHostSelectorStrategy=roundRobin
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: software.amazon.jdbc.Driver
    type: org.springframework.jdbc.datasource.SimpleDriverDataSource
    configuration:
      exception-override-class-name: software.amazon.jdbc.util.HikariCPSQLException
      max-pool-size: 30
      max-lifetime: 1260000
      auto-commit: false
      maximum-pool-size: 3
      data-source-properties:
        keepSessionStateOnFailover: true
logging:
  level:
    root: DEBUG
    web: DEBUG
    org.mybatis: DEBUG
    software.amazon.jdbc: TRACE
    dev.higuchi.homeexpense.postgresql.mybatisadapter.datasource: TRACE
