spring:
  datasource:
    url: jdbc:aws-wrapper:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: software.amazon.jdbc.Driver
    type: org.springframework.jdbc.datasource.SimpleDriverDataSource
#    hikari:
#      data-source-properties:
#        wrapperPlugins: failover,readWriteSplitting
#        wrapperDialect: aurora-pg
#      max-lifetime: 840000
#      minimum-idle: 20
#      maximum-pool-size: 20
#      idle-timeout: 900000
#      read-only: true