quarkus.datasource.db-kind = postgresql
quarkus.datasource.username = expense
quarkus.datasource.password = password
quarkus.datasource.jdbc.url = jdbc:postgresql://localhost:5432/expense
quarkus.datasource.jdbc.min-size = 5
quarkus.datasource.jdbc.max-size = 20
quarkus.datasource.jdbc.acquisition-timeout = 5S
quarkus.http.port = 8080
quarkus.http.enable-compression = true
quarkus.http.cors.enabled = true
quarkus.http.cors.origins = http://localhost:3000
quarkus.log.level = DEBUG
%dev.quarkus.log.console.json.enabled = false
%test.quarkus.datasource.jdbc.url = jdbc:postgresql://localhost:5432/expense_test
%test.quarkus.log.console.json.enabled = false
