ALTER TABLE expense.expense ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE expense.attribute ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE expense.fixed_expense ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE expense.variable_expense ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE expense.income_attribute ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE expense.income ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
