flyway.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
flyway.user=${DB_USER}
flyway.password=${DB_PASSWORD}
flyway.connectRetries=60
flyway.cleanDisabled=true
flyway.locations=filesystem:./sql
flyway.baselineVersion=0.0.0
flyway.schemas=expense
flyway.defaultSchema=public
