[versions]
# Plugins
com-diffplug-spotless = "8.1.0"

# Dependencies
flyway = "11.20.0"
logback = "1.5.23"
logstash-logback-encoder = "9.0"
mysql-connector = "9.4.0"
postgresql = "42.7.8"
slf4j = "2.0.17"

[libraries]
flyway-core = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }
flyway-database-postgresql = { module = "org.flywaydb:flyway-database-postgresql", version.ref = "flyway" }
flyway-mysql = { module = "org.flywaydb:flyway-mysql", version.ref = "flyway" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
logstash-logback-encoder = { module = "net.logstash.logback:logstash-logback-encoder", version.ref = "logstash-logback-encoder" }
mysql-connector-j = { module = "com.mysql:mysql-connector-j", version.ref = "mysql-connector" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }

[plugins]
com-diffplug-spotless = { id = "com.diffplug.spotless", version.ref = "com-diffplug-spotless" }
