name: Continuous Integration
run-name: Continuous Integration
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: sdkman/sdkman-action@main
        id: sdkman
        with:
          candidate: java
          version: 21.0.7.crac-zulu
      - name: Gradle build
        continue-on-error: true
        run: |
          source "/home/runner/.sdkman/bin/sdkman-init.sh"
          ls -la $JAVA_HOME/lib/criu
          java -version
          ./gradlew --console=plain --no-daemon -q spring-boot:build -x check
          ls -la $JAVA_HOME/lib/criu
          sudo chown root:root $JAVA_HOME/lib/criu
          sudo chmod u+s $JAVA_HOME/lib/criu
          ls -ltar
          java -Dspring.context.checkpoint=onRefresh -XX:CRaCEngine=warp -XX:CRaCCheckpointTo=./my_checkpoint -jar spring-boot/build/libs/spring-boot-0.0.1-SNAPSHOT.jar | cat
          ls -ltar ./my_checkpoint
        working-directory: app
  build-and-lint-docker-image:
    uses: yhiguchi-dev/reusable-workflow/.github/workflows/docker-image.yaml@main
    with:
      build-context: ${{ matrix.build-context }}
      version: lint
      platform: ${{ matrix.platform }}
    needs:
      - lint
    strategy:
      fail-fast: false
      matrix:
        build-context:
          - app
          - flyway
        platform:
          - linux/amd64