name: Continuous Integration
run-name: Continuous Integration
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: sdkman/sdkman-action@main
        id: sdkman
        with:
          candidate: java
          version: 21.0.7.crac-zulu
      - run: java -version
      - name: Gradle lint
        run: ./gradlew --console=plain --no-daemon --enable-preview -q build -x check
        working-directory: app
      - name: checkpoint
        run: |
          ls -ltar
          java -Dspring.context.checkpoint=onRefresh -XX:CRaCCheckpointTo=./my_checkpoint -jar spring-boot/build/libs/spring-boot-0.0.1-SNAPSHOT.jar
        working-directory: app
  build-and-lint-docker-image:
    uses: yhiguchi-dev/reusable-workflow/.github/workflows/docker-image.yaml@main
    with:
      build-context: ${{ matrix.build-context }}
      version: lint
      platform: ${{ matrix.platform }}
    needs:
      - lint
    strategy:
      fail-fast: false
      matrix:
        build-context:
          - app/spring-boot
          - flyway
        platform:
          - linux/amd64