name: CI
run-name: ${{ github.workflow }} (${{ github.ref_name }})
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  NEXT_PUBLIC_BACKEND_URL: ${{ secrets.BACKEND_URL }}
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        graalvm-version:
          - 22.3.1
        java-version:
          - 17
    env:
      TARGET_DIR: quarkus
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.sha }}
      - uses: actions/checkout@v3
      - name: Check changed files
        run: |
          git diff --name-only --relative=$TARGET_DIR ${{ github.event.pull_request.base.sha }} HEAD
      - uses: graalvm/setup-graalvm@v1
        with:
          version: ${{ matrix.graalvm-version }}
          java-version: ${{ matrix.java-version }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: gradle
      - name: Show Version
        run: |
          java --version
      - name: Gradle lint
        run: ./gradlew check
        working-directory: quarkus
  build:
    runs-on: ubuntu-latest
    needs:
      - lint
    strategy:
      fail-fast: false
      matrix:
        build-context:
          - quarkus
          - flyway
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build ${{ matrix.build-context }}
        uses: docker/build-push-action@v3
        with:
          context: ./${{ matrix.build-context }}
          load: true
          tags: ghcr.io/${{ github.repository }}-${{ matrix.build-context }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/${{ github.repository }}-${{ matrix.build-context }}:latest
          format: table
          exit-code: 1
          ignore-unfixed: true
          vuln-type: os,library
          severity: CRITICAL,HIGH