name: Continuous Integration
run-name: Continuous Integration
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Gradle lint
        run: ./gradlew --console=plain --no-daemon -q check
        working-directory: app
  build-and-lint:
    uses: yhiguchi-dev/reusable-workflow/.github/workflows/docker-image.yaml@main
    with:
      build-context: ${{ matrix.build-context }}
      version: ${{ needs.pre-build-and-push.outputs.version }}
      platform: ${{ matrix.platform }}
    needs:
      - pre-build-and-push
    strategy:
      fail-fast: false
      matrix:
        build-context:
          - app
          - flyway
        platform:
          - linux/amd64