name: CI
run-name: Push ${{ github.workflow }} (${{ github.ref_name }})
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  lint:
    uses: yhiguchi-dev/reusable-workflow/.github/workflows/lint-with-gradle.yaml@main
    with:
      node-version: ${{ matrix.node-version }}
      lint-command: lint
      working-directory: app
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 20

  pre-build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set-version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - name: Set Version
        id: set-version
        run: |
          echo "version=$(./gradlew printVersion)" >> "${GITHUB_OUTPUT}"
        working-directory: app
  build:
    uses: yhiguchi-dev/reusable-workflow/.github/workflows/docker-image-push-to-ghcr.yaml@main
    with:
      build-context: ${{ matrix.build-context }}
      version: ${{ needs.pre-build.outputs.version }}
    needs:
      - pre-build
      - lint
    strategy:
      fail-fast: false
      matrix:
        build-context:
          - app
