name: CI
run-name: Push Docker Image
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Gradle lint
        run: ./gradlew check
        working-directory: app

  pre-build-and-push:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set-version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Set Version
        id: set-version
        run: |
          echo "version=$(./gradlew --console=plain --no-daemon -q printVersion)" >> "${GITHUB_OUTPUT}"
        working-directory: app
  build-and-push:
    uses: yhiguchi-dev/reusable-workflow/.github/workflows/docker-image-push-to-ghcr.yaml@main
    with:
      build-context: ${{ matrix.build-context }}
      version: ${{ needs.pre-build.outputs.version }}
    needs:
      - pre-build
      - lint
    strategy:
      fail-fast: false
      matrix:
        build-context:
          - app
