name: Docker Image CI
run-name: ${{ github.workflow }} (${{ github.ref_name }})
on:
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  NEXT_PUBLIC_BACKEND_URL: ${{ secrets.BACKEND_URL }}
jobs:
  push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build-context:
          - quarkus
          - database
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build ${{ matrix.build-context }}
        uses: docker/build-push-action@v4
        with:
          context: ./${{ matrix.build-context }}
          load: true
          tags: ghcr.io/${{ github.repository }}-${{ matrix.build-context }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Push ${{ matrix.build-context }}
        uses: docker/build-push-action@v4
        with:
          context: ./${{ matrix.build-context }}
          push: true
          tags: ghcr.io/${{ github.repository }}-${{ matrix.build-context }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max